apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: mypod
          labels:
            app: myapp
        spec:
          restartPolicy: OnFailure
          containers:
            - name: hello
              image: busybox
              command: [ "/bin/sh","-c" ]
              args:           
                - date; 
                  echo "Hello from the Kubernetes cluster";
