apiVersion: apps/v1
kind: Deployment
metadata:
  name: np-deployment
  labels:
	app: frontend
spec:
  replicas: 3
  selector:
	matchLabels:
	  app: frontend
  template:
	metadata:
	  labels:
		app: frontend 
	spec:
	  containers:
	  - name: myapp-cont
		image: lerndevops/samplepyapp:v2
		ports:
		- containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: npservice
spec:
  type: LoadBalancer
  selector:
	app: frontend
  ports:
   - protocol: TCP
	 port: 3000
