
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeployment
spec: 
  replicas: 4
  selector:
    matchLabels:
      app: javawebapp
  strategy:
    type: RollingUpdate
    rollingUpdate:  
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapp 
    spec: 
      containers:
      - name: javawebappcontainer
        image:  myacrrepo2310.azurecr.io/my-web:v1
        ports:
        - containerPort: 8080
---        
apiVersion: v1
kind: Service
metadata: 
  name: javawebappservice
spec:
  type: LoadBalancer
  selector: 
    app: javawebapp
  ports:
  - port: 8080
