apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  containers:
  - name: main-app
    image: nginx
    ports:
    - containerPort: 80
  initContainers:
  - name: init-myservice
    image: busybox
    command: ['sh', '-c', 'echo "Init container running..."; sleep 5']
