apiVersion: batch/v1
kind: Job
metadata:
  name: countdown
spec:
  backoffLimit: 4 #to specify the number of retries before considering a Job as failed.
  template:
    metadata:
      name: countdown
    spec:
      restartPolicy: Never
      containers:
        - name: counter
          image: centos:7         
          command:
          - "bin/bash"
          - "-c"
          - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
