apiVersion: v1
kind: Pod
metadata:
  name: multi-cont
spec:
  restartPolicy: Never
  containers:
  - name: nginx
    image: nginx
    ports:
     - containerPort: 80
  - name: alpine
    image: alpine
    command: ['sh', '-c', 'sleep 180']
