apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginxrs
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata: 
      name: nginxpod
      labels:
        app: web
    spec:
      containers:
        - name: nginxcont
          image: nginx
          ports:
            - containerPort: 80
