apiVersion: v1
kind: Pod
metadata:
  name: nginx-readiness-success
  labels:
    app: nginx-readiness-success
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 2
