apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxrc
spec:
  replicas: 4
  selector:
    app: web
  template:
    metadata:
      name: nginxpod   
      labels:
        app: web
    spec:
      containers:
        - name: nginxcont
          image: nginx
          ports:
            - containerPort: 80
