apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-readiness-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-readiness
  template:
    metadata:
      labels:
        app: nginx-readiness
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /invalidpath   # Will fail for all pods
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-readiness-svc
spec:
  type: LoadBalancer
  selector:
    app: nginx-readiness
  ports:
    - port: 80
      targetPort: 80
