apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-liveness-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-liveness
  template:
    metadata:
      labels:
        app: nginx-liveness
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /            # Pod 1 → succeeds
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-liveness-svc
spec:
  type: LoadBalancer
  selector:
    app: nginx-liveness
  ports:
    - port: 80
      targetPort: 80
