apiVersion: v1
kind: Pod
metadata:
  name: nginx-readiness-failure
  labels:
    app: nginx-readiness-failure
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    readinessProbe:
      httpGet:
        path: /invalidpath   # Wrong path
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 2
